// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pim-service/product.proto

package pimpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SkuCode              string       `protobuf:"bytes,2,opt,name=skuCode,proto3" json:"skuCode,omitempty"`
	Name                 string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	UniqueName           string       `protobuf:"bytes,5,opt,name=uniqueName,proto3" json:"uniqueName,omitempty"`
	Active               bool         `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	Variation            []*Variation `protobuf:"bytes,7,rep,name=variation,proto3" json:"variation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_d9dcadf5b7019c02, []int{0}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetUniqueName() string {
	if m != nil {
		return m.UniqueName
	}
	return ""
}

func (m *Product) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Product) GetVariation() []*Variation {
	if m != nil {
		return m.Variation
	}
	return nil
}

type ProductList struct {
	Product              []*Product `protobuf:"bytes,1,rep,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductList) Reset()         { *m = ProductList{} }
func (m *ProductList) String() string { return proto.CompactTextString(m) }
func (*ProductList) ProtoMessage()    {}
func (*ProductList) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_d9dcadf5b7019c02, []int{1}
}
func (m *ProductList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductList.Unmarshal(m, b)
}
func (m *ProductList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductList.Marshal(b, m, deterministic)
}
func (dst *ProductList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductList.Merge(dst, src)
}
func (m *ProductList) XXX_Size() int {
	return xxx_messageInfo_ProductList.Size(m)
}
func (m *ProductList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductList.DiscardUnknown(m)
}

var xxx_messageInfo_ProductList proto.InternalMessageInfo

func (m *ProductList) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateRequest struct {
	SkuCode              string   `protobuf:"bytes,1,opt,name=skuCode,proto3" json:"skuCode,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UniqueName           string   `protobuf:"bytes,4,opt,name=uniqueName,proto3" json:"uniqueName,omitempty"`
	Active               bool     `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_d9dcadf5b7019c02, []int{2}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateRequest) GetUniqueName() string {
	if m != nil {
		return m.UniqueName
	}
	return ""
}

func (m *CreateRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type UpdateRequest struct {
	SkuCode              string   `protobuf:"bytes,1,opt,name=skuCode,proto3" json:"skuCode,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UniqueName           string   `protobuf:"bytes,4,opt,name=uniqueName,proto3" json:"uniqueName,omitempty"`
	Active               bool     `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_d9dcadf5b7019c02, []int{3}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateRequest) GetUniqueName() string {
	if m != nil {
		return m.UniqueName
	}
	return ""
}

func (m *UpdateRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type QueryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SkuCode              string   `protobuf:"bytes,2,opt,name=skuCode,proto3" json:"skuCode,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_d9dcadf5b7019c02, []int{4}
}
func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (dst *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(dst, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryRequest) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *QueryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_d9dcadf5b7019c02, []int{5}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "pim.v1.Product")
	proto.RegisterType((*ProductList)(nil), "pim.v1.ProductList")
	proto.RegisterType((*CreateRequest)(nil), "pim.v1.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "pim.v1.UpdateRequest")
	proto.RegisterType((*QueryRequest)(nil), "pim.v1.QueryRequest")
	proto.RegisterType((*DeleteRequest)(nil), "pim.v1.DeleteRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Product, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Product, error)
	Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Product, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductList, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ProductList, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/pim.v1.ProductService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/pim.v1.ProductService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/pim.v1.ProductService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductList, error) {
	out := new(ProductList)
	err := c.cc.Invoke(ctx, "/pim.v1.ProductService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ProductList, error) {
	out := new(ProductList)
	err := c.cc.Invoke(ctx, "/pim.v1.ProductService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pim.v1.ProductService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	Create(context.Context, *CreateRequest) (*Product, error)
	Update(context.Context, *UpdateRequest) (*Product, error)
	Get(context.Context, *Empty) (*Product, error)
	List(context.Context, *Empty) (*ProductList, error)
	Query(context.Context, *QueryRequest) (*ProductList, error)
	Delete(context.Context, *DeleteRequest) (*Empty, error)
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.ProductService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.ProductService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.ProductService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Get(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.ProductService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.ProductService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.ProductService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pim.v1.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProductService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProductService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProductService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProductService_List_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _ProductService_Query_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProductService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pim-service/product.proto",
}

func init() { proto.RegisterFile("pim-service/product.proto", fileDescriptor_product_d9dcadf5b7019c02) }

var fileDescriptor_product_d9dcadf5b7019c02 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xcb, 0x8e, 0x94, 0x40,
	0x14, 0x86, 0x9b, 0xbb, 0x73, 0xda, 0x1e, 0x93, 0xf2, 0x92, 0x92, 0xc4, 0x91, 0xb0, 0xb1, 0x4d,
	0x1c, 0xd4, 0xd6, 0x85, 0x89, 0x3b, 0x47, 0xe3, 0x66, 0x62, 0x14, 0x2f, 0x0b, 0x77, 0x0c, 0x9c,
	0x45, 0x45, 0x81, 0x6a, 0x28, 0x48, 0xfa, 0x49, 0x7c, 0x14, 0xdf, 0xc6, 0x67, 0x31, 0x54, 0x51,
	0xe1, 0x12, 0x5a, 0x17, 0x6e, 0xdc, 0x75, 0x9d, 0xf3, 0xff, 0xa7, 0xeb, 0xff, 0x4e, 0x05, 0xb8,
	0xcb, 0x59, 0x7e, 0x5e, 0x63, 0xd5, 0xb2, 0x14, 0x1f, 0xf3, 0xaa, 0xcc, 0x9a, 0x54, 0x44, 0xbc,
	0x2a, 0x45, 0x49, 0x5c, 0xce, 0xf2, 0xa8, 0x7d, 0xea, 0xd3, 0xb1, 0x24, 0x2d, 0xf3, 0xbc, 0x2c,
	0x94, 0xc2, 0x3f, 0x5b, 0x30, 0x9f, 0x8b, 0x03, 0x47, 0xd5, 0x0f, 0x7f, 0x19, 0xe0, 0xbd, 0x57,
	0x65, 0x72, 0x0a, 0x26, 0xcb, 0xa8, 0x11, 0x18, 0xdb, 0x93, 0xd8, 0x64, 0x19, 0xa1, 0xe0, 0xd5,
	0xdf, 0x9a, 0x8b, 0x32, 0x43, 0x6a, 0xca, 0xa2, 0x3e, 0x12, 0x02, 0x76, 0x91, 0xe4, 0x48, 0x2d,
	0x59, 0x96, 0xbf, 0x49, 0x00, 0xeb, 0x0c, 0xeb, 0xb4, 0x62, 0x5c, 0xb0, 0xb2, 0xa0, 0xb6, 0x6c,
	0x8d, 0x4b, 0xe4, 0x0c, 0xa0, 0x29, 0xd8, 0xbe, 0xc1, 0x77, 0x9d, 0xd7, 0x91, 0x82, 0x51, 0x85,
	0xdc, 0x01, 0x37, 0x49, 0x05, 0x6b, 0x91, 0xba, 0x81, 0xb1, 0xbd, 0x16, 0xf7, 0x27, 0xf2, 0x12,
	0x4e, 0xda, 0xa4, 0x62, 0x89, 0x9c, 0xeb, 0x05, 0xd6, 0x76, 0xbd, 0xbb, 0x17, 0xa9, 0xe4, 0x51,
	0x1f, 0xe9, 0x53, 0x97, 0xe8, 0x8b, 0x16, 0xc5, 0x83, 0x3e, 0x7c, 0x01, 0xeb, 0x3e, 0xdf, 0x25,
	0xab, 0x05, 0x79, 0x08, 0x5e, 0x6f, 0xa1, 0x86, 0x9c, 0x74, 0x43, 0x4f, 0xea, 0x55, 0xb1, 0xee,
	0x87, 0x3f, 0x0c, 0xd8, 0x5c, 0x54, 0x98, 0x08, 0x8c, 0x71, 0xdf, 0x60, 0x2d, 0xc6, 0x40, 0x8c,
	0x65, 0x20, 0xe6, 0x71, 0x20, 0xd6, 0xdf, 0x80, 0xd8, 0x7f, 0x00, 0xe2, 0x8c, 0x81, 0xc8, 0x9b,
	0x7d, 0xe6, 0xd9, 0x7f, 0x78, 0xb3, 0x4b, 0xb8, 0xfe, 0xa1, 0xc1, 0xea, 0xa0, 0xef, 0xf5, 0x4f,
	0x4f, 0x2a, 0xbc, 0x0f, 0x9b, 0xd7, 0xf8, 0x1d, 0x87, 0x98, 0xb3, 0x71, 0xbb, 0x9f, 0x26, 0x9c,
	0xf6, 0x7b, 0xfb, 0xa8, 0xde, 0x38, 0xd9, 0x81, 0xab, 0x96, 0x46, 0x6e, 0xeb, 0xcd, 0x4e, 0x96,
	0xe8, 0xcf, 0x17, 0x1e, 0xae, 0x3a, 0x8f, 0xc2, 0x39, 0x78, 0x26, 0x78, 0x97, 0x3c, 0x0f, 0xc0,
	0x7a, 0x8b, 0x82, 0x6c, 0x74, 0xe7, 0x4d, 0xce, 0xc5, 0x61, 0x49, 0xf8, 0x08, 0x6c, 0xf9, 0xf2,
	0x66, 0xca, 0x9b, 0x33, 0x65, 0xa7, 0x09, 0x57, 0xe4, 0x39, 0x38, 0x12, 0x20, 0xb9, 0xa5, 0xfb,
	0x63, 0x9e, 0xc7, 0x5c, 0x4f, 0xc0, 0x55, 0xa0, 0x86, 0x00, 0x13, 0x70, 0xfe, 0xf4, 0xcf, 0xc3,
	0xd5, 0x2b, 0xef, 0xab, 0xc3, 0x59, 0xce, 0xaf, 0xae, 0x5c, 0xf9, 0x1d, 0x78, 0xf6, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x79, 0x54, 0xc5, 0x5c, 0x66, 0x04, 0x00, 0x00,
}
