// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pim-service/product-type.proto

package pimpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueType int32

const (
	ValueType_TEXT    ValueType = 0
	ValueType_NUMBER  ValueType = 1
	ValueType_BOOLEAN ValueType = 2
)

var ValueType_name = map[int32]string{
	0: "TEXT",
	1: "NUMBER",
	2: "BOOLEAN",
}
var ValueType_value = map[string]int32{
	"TEXT":    0,
	"NUMBER":  1,
	"BOOLEAN": 2,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_product_type_80017bbb3ef13153, []int{0}
}

type CreateRequest struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Active               bool             `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XVersion             int32            `protobuf:"varint,6,opt,name=_version,json=Version,proto3" json:"_version,omitempty"`
	XCreatedAt           int64            `protobuf:"varint,7,opt,name=_createdAt,json=CreatedAt,proto3" json:"_createdAt,omitempty"`
	XUpdatedAt           int64            `protobuf:"varint,8,opt,name=_updatedAt,json=UpdatedAt,proto3" json:"_updatedAt,omitempty"`
	XCreatedBy           string           `protobuf:"bytes,9,opt,name=_createdBy,json=CreatedBy,proto3" json:"_createdBy,omitempty"`
	XUpdatedBy           string           `protobuf:"bytes,10,opt,name=_updatedBy,json=UpdatedBy,proto3" json:"_updatedBy,omitempty"`
	Specification        []*Specification `protobuf:"bytes,11,rep,name=specification,proto3" json:"specification,omitempty"`
	Variation            []*Variation     `protobuf:"bytes,12,rep,name=variation,proto3" json:"variation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_type_80017bbb3ef13153, []int{0}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *CreateRequest) GetXVersion() int32 {
	if m != nil {
		return m.XVersion
	}
	return 0
}

func (m *CreateRequest) GetXCreatedAt() int64 {
	if m != nil {
		return m.XCreatedAt
	}
	return 0
}

func (m *CreateRequest) GetXUpdatedAt() int64 {
	if m != nil {
		return m.XUpdatedAt
	}
	return 0
}

func (m *CreateRequest) GetXCreatedBy() string {
	if m != nil {
		return m.XCreatedBy
	}
	return ""
}

func (m *CreateRequest) GetXUpdatedBy() string {
	if m != nil {
		return m.XUpdatedBy
	}
	return ""
}

func (m *CreateRequest) GetSpecification() []*Specification {
	if m != nil {
		return m.Specification
	}
	return nil
}

func (m *CreateRequest) GetVariation() []*Variation {
	if m != nil {
		return m.Variation
	}
	return nil
}

type UpdateRequest struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Active               bool             `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XVersion             int32            `protobuf:"varint,6,opt,name=_version,json=Version,proto3" json:"_version,omitempty"`
	XCreatedAt           int64            `protobuf:"varint,7,opt,name=_createdAt,json=CreatedAt,proto3" json:"_createdAt,omitempty"`
	XUpdatedAt           int64            `protobuf:"varint,8,opt,name=_updatedAt,json=UpdatedAt,proto3" json:"_updatedAt,omitempty"`
	XCreatedBy           string           `protobuf:"bytes,9,opt,name=_createdBy,json=CreatedBy,proto3" json:"_createdBy,omitempty"`
	XUpdatedBy           string           `protobuf:"bytes,10,opt,name=_updatedBy,json=UpdatedBy,proto3" json:"_updatedBy,omitempty"`
	Specification        []*Specification `protobuf:"bytes,11,rep,name=specification,proto3" json:"specification,omitempty"`
	Variation            []*Variation     `protobuf:"bytes,12,rep,name=variation,proto3" json:"variation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_type_80017bbb3ef13153, []int{1}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *UpdateRequest) GetXVersion() int32 {
	if m != nil {
		return m.XVersion
	}
	return 0
}

func (m *UpdateRequest) GetXCreatedAt() int64 {
	if m != nil {
		return m.XCreatedAt
	}
	return 0
}

func (m *UpdateRequest) GetXUpdatedAt() int64 {
	if m != nil {
		return m.XUpdatedAt
	}
	return 0
}

func (m *UpdateRequest) GetXCreatedBy() string {
	if m != nil {
		return m.XCreatedBy
	}
	return ""
}

func (m *UpdateRequest) GetXUpdatedBy() string {
	if m != nil {
		return m.XUpdatedBy
	}
	return ""
}

func (m *UpdateRequest) GetSpecification() []*Specification {
	if m != nil {
		return m.Specification
	}
	return nil
}

func (m *UpdateRequest) GetVariation() []*Variation {
	if m != nil {
		return m.Variation
	}
	return nil
}

type QueryReqeust struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReqeust) Reset()         { *m = QueryReqeust{} }
func (m *QueryReqeust) String() string { return proto.CompactTextString(m) }
func (*QueryReqeust) ProtoMessage()    {}
func (*QueryReqeust) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_type_80017bbb3ef13153, []int{2}
}
func (m *QueryReqeust) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReqeust.Unmarshal(m, b)
}
func (m *QueryReqeust) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReqeust.Marshal(b, m, deterministic)
}
func (dst *QueryReqeust) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReqeust.Merge(dst, src)
}
func (m *QueryReqeust) XXX_Size() int {
	return xxx_messageInfo_QueryReqeust.Size(m)
}
func (m *QueryReqeust) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReqeust.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReqeust proto.InternalMessageInfo

func (m *QueryReqeust) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryReqeust) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueryReqeust) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_type_80017bbb3ef13153, []int{3}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Specification struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UniqueName  string `protobuf:"bytes,4,opt,name=uniqueName,proto3" json:"uniqueName,omitempty"`
	// SpecificationConstraint constraint = 5;
	ValueType            ValueType `protobuf:"varint,6,opt,name=valueType,proto3,enum=pim.v1.productType.ValueType" json:"valueType,omitempty"`
	Value                string    `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_type_80017bbb3ef13153, []int{4}
}
func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (dst *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(dst, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Specification) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Specification) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Specification) GetUniqueName() string {
	if m != nil {
		return m.UniqueName
	}
	return ""
}

func (m *Specification) GetValueType() ValueType {
	if m != nil {
		return m.ValueType
	}
	return ValueType_TEXT
}

func (m *Specification) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Variation struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UniqueName           string    `protobuf:"bytes,4,opt,name=uniqueName,proto3" json:"uniqueName,omitempty"`
	ValueType            ValueType `protobuf:"varint,5,opt,name=valueType,proto3,enum=pim.v1.productType.ValueType" json:"valueType,omitempty"`
	Value                string    `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Variation) Reset()         { *m = Variation{} }
func (m *Variation) String() string { return proto.CompactTextString(m) }
func (*Variation) ProtoMessage()    {}
func (*Variation) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_type_80017bbb3ef13153, []int{5}
}
func (m *Variation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variation.Unmarshal(m, b)
}
func (m *Variation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variation.Marshal(b, m, deterministic)
}
func (dst *Variation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variation.Merge(dst, src)
}
func (m *Variation) XXX_Size() int {
	return xxx_messageInfo_Variation.Size(m)
}
func (m *Variation) XXX_DiscardUnknown() {
	xxx_messageInfo_Variation.DiscardUnknown(m)
}

var xxx_messageInfo_Variation proto.InternalMessageInfo

func (m *Variation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Variation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Variation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Variation) GetUniqueName() string {
	if m != nil {
		return m.UniqueName
	}
	return ""
}

func (m *Variation) GetValueType() ValueType {
	if m != nil {
		return m.ValueType
	}
	return ValueType_TEXT
}

func (m *Variation) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ProductType struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	//  string uniqueName = 4; // can be used as slug name in urls
	Active               bool             `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XVersion             int32            `protobuf:"varint,6,opt,name=_version,json=Version,proto3" json:"_version,omitempty"`
	XCreatedAt           int64            `protobuf:"varint,7,opt,name=_createdAt,json=CreatedAt,proto3" json:"_createdAt,omitempty"`
	XUpdatedAt           int64            `protobuf:"varint,8,opt,name=_updatedAt,json=UpdatedAt,proto3" json:"_updatedAt,omitempty"`
	XCreatedBy           string           `protobuf:"bytes,9,opt,name=_createdBy,json=CreatedBy,proto3" json:"_createdBy,omitempty"`
	XUpdatedBy           string           `protobuf:"bytes,10,opt,name=_updatedBy,json=UpdatedBy,proto3" json:"_updatedBy,omitempty"`
	Specification        []*Specification `protobuf:"bytes,11,rep,name=specification,proto3" json:"specification,omitempty"`
	Variation            []*Variation     `protobuf:"bytes,12,rep,name=variation,proto3" json:"variation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProductType) Reset()         { *m = ProductType{} }
func (m *ProductType) String() string { return proto.CompactTextString(m) }
func (*ProductType) ProtoMessage()    {}
func (*ProductType) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_type_80017bbb3ef13153, []int{6}
}
func (m *ProductType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductType.Unmarshal(m, b)
}
func (m *ProductType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductType.Marshal(b, m, deterministic)
}
func (dst *ProductType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductType.Merge(dst, src)
}
func (m *ProductType) XXX_Size() int {
	return xxx_messageInfo_ProductType.Size(m)
}
func (m *ProductType) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductType.DiscardUnknown(m)
}

var xxx_messageInfo_ProductType proto.InternalMessageInfo

func (m *ProductType) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProductType) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *ProductType) GetXVersion() int32 {
	if m != nil {
		return m.XVersion
	}
	return 0
}

func (m *ProductType) GetXCreatedAt() int64 {
	if m != nil {
		return m.XCreatedAt
	}
	return 0
}

func (m *ProductType) GetXUpdatedAt() int64 {
	if m != nil {
		return m.XUpdatedAt
	}
	return 0
}

func (m *ProductType) GetXCreatedBy() string {
	if m != nil {
		return m.XCreatedBy
	}
	return ""
}

func (m *ProductType) GetXUpdatedBy() string {
	if m != nil {
		return m.XUpdatedBy
	}
	return ""
}

func (m *ProductType) GetSpecification() []*Specification {
	if m != nil {
		return m.Specification
	}
	return nil
}

func (m *ProductType) GetVariation() []*Variation {
	if m != nil {
		return m.Variation
	}
	return nil
}

type ProductTypeList struct {
	ProductType          []*ProductType `protobuf:"bytes,1,rep,name=productType,proto3" json:"productType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProductTypeList) Reset()         { *m = ProductTypeList{} }
func (m *ProductTypeList) String() string { return proto.CompactTextString(m) }
func (*ProductTypeList) ProtoMessage()    {}
func (*ProductTypeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_type_80017bbb3ef13153, []int{7}
}
func (m *ProductTypeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductTypeList.Unmarshal(m, b)
}
func (m *ProductTypeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductTypeList.Marshal(b, m, deterministic)
}
func (dst *ProductTypeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductTypeList.Merge(dst, src)
}
func (m *ProductTypeList) XXX_Size() int {
	return xxx_messageInfo_ProductTypeList.Size(m)
}
func (m *ProductTypeList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductTypeList.DiscardUnknown(m)
}

var xxx_messageInfo_ProductTypeList proto.InternalMessageInfo

func (m *ProductTypeList) GetProductType() []*ProductType {
	if m != nil {
		return m.ProductType
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "pim.v1.productType.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "pim.v1.productType.UpdateRequest")
	proto.RegisterType((*QueryReqeust)(nil), "pim.v1.productType.QueryReqeust")
	proto.RegisterType((*DeleteRequest)(nil), "pim.v1.productType.DeleteRequest")
	proto.RegisterType((*Specification)(nil), "pim.v1.productType.Specification")
	proto.RegisterType((*Variation)(nil), "pim.v1.productType.Variation")
	proto.RegisterType((*ProductType)(nil), "pim.v1.productType.ProductType")
	proto.RegisterType((*ProductTypeList)(nil), "pim.v1.productType.ProductTypeList")
	proto.RegisterEnum("pim.v1.productType.ValueType", ValueType_name, ValueType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductTypeServiceClient is the client API for ProductTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductTypeServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ProductType, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ProductType, error)
	Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductType, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductTypeList, error)
	Query(ctx context.Context, in *QueryReqeust, opts ...grpc.CallOption) (*ProductTypeList, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error)
}

type productTypeServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductTypeServiceClient(cc *grpc.ClientConn) ProductTypeServiceClient {
	return &productTypeServiceClient{cc}
}

func (c *productTypeServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ProductType, error) {
	out := new(ProductType)
	err := c.cc.Invoke(ctx, "/pim.v1.productType.ProductTypeService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productTypeServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ProductType, error) {
	out := new(ProductType)
	err := c.cc.Invoke(ctx, "/pim.v1.productType.ProductTypeService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productTypeServiceClient) Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductType, error) {
	out := new(ProductType)
	err := c.cc.Invoke(ctx, "/pim.v1.productType.ProductTypeService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productTypeServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProductTypeList, error) {
	out := new(ProductTypeList)
	err := c.cc.Invoke(ctx, "/pim.v1.productType.ProductTypeService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productTypeServiceClient) Query(ctx context.Context, in *QueryReqeust, opts ...grpc.CallOption) (*ProductTypeList, error) {
	out := new(ProductTypeList)
	err := c.cc.Invoke(ctx, "/pim.v1.productType.ProductTypeService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productTypeServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pim.v1.productType.ProductTypeService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductTypeServiceServer is the server API for ProductTypeService service.
type ProductTypeServiceServer interface {
	Create(context.Context, *CreateRequest) (*ProductType, error)
	Update(context.Context, *UpdateRequest) (*ProductType, error)
	Get(context.Context, *Empty) (*ProductType, error)
	List(context.Context, *Empty) (*ProductTypeList, error)
	Query(context.Context, *QueryReqeust) (*ProductTypeList, error)
	Delete(context.Context, *DeleteRequest) (*Empty, error)
}

func RegisterProductTypeServiceServer(s *grpc.Server, srv ProductTypeServiceServer) {
	s.RegisterService(&_ProductTypeService_serviceDesc, srv)
}

func _ProductTypeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductTypeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.productType.ProductTypeService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductTypeServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductTypeService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductTypeServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.productType.ProductTypeService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductTypeServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductTypeService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductTypeServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.productType.ProductTypeService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductTypeServiceServer).Get(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductTypeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductTypeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.productType.ProductTypeService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductTypeServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductTypeService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReqeust)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductTypeServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.productType.ProductTypeService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductTypeServiceServer).Query(ctx, req.(*QueryReqeust))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductTypeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductTypeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pim.v1.productType.ProductTypeService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductTypeServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductTypeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pim.v1.productType.ProductTypeService",
	HandlerType: (*ProductTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProductTypeService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProductTypeService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProductTypeService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProductTypeService_List_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _ProductTypeService_Query_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProductTypeService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pim-service/product-type.proto",
}

func init() {
	proto.RegisterFile("pim-service/product-type.proto", fileDescriptor_product_type_80017bbb3ef13153)
}

var fileDescriptor_product_type_80017bbb3ef13153 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xb5, 0x2c, 0x4b, 0xb6, 0x46, 0x71, 0x6a, 0x96, 0x52, 0x54, 0x43, 0x12, 0x55, 0xbd, 0x98,
	0x42, 0x54, 0x9a, 0x1e, 0x7a, 0x68, 0x2e, 0x56, 0x6a, 0x02, 0x25, 0x75, 0xd2, 0x8d, 0x1d, 0x4a,
	0x2f, 0xc1, 0x91, 0xb6, 0xb0, 0x10, 0x59, 0x6b, 0x7d, 0x18, 0xf4, 0x0f, 0x4a, 0xff, 0x52, 0xaf,
	0x3d, 0xf4, 0x67, 0x15, 0xed, 0x5a, 0xf5, 0xaa, 0x55, 0x88, 0x0f, 0x01, 0x5f, 0x72, 0xf3, 0xce,
	0xbc, 0xf7, 0x98, 0x7d, 0x33, 0x9a, 0x35, 0xec, 0x33, 0x1a, 0x1e, 0x26, 0x24, 0x5e, 0x52, 0x9f,
	0xbc, 0x66, 0x71, 0x14, 0x64, 0x7e, 0x7a, 0x98, 0xe6, 0x8c, 0xb8, 0x2c, 0x8e, 0xd2, 0x08, 0x21,
	0x46, 0x43, 0x77, 0xf9, 0xc6, 0x5d, 0xa5, 0x26, 0x39, 0x23, 0x7d, 0x4b, 0xe6, 0xf8, 0x51, 0x18,
	0x46, 0x73, 0x81, 0x76, 0x7e, 0xa8, 0xd0, 0x3d, 0x89, 0xc9, 0x2c, 0x25, 0x98, 0x2c, 0x32, 0x92,
	0xa4, 0x68, 0x17, 0x9a, 0x34, 0xb0, 0x14, 0x5b, 0x19, 0x18, 0xb8, 0x49, 0x03, 0x84, 0xa0, 0x35,
	0x9f, 0x85, 0xc4, 0x6a, 0xf2, 0x08, 0xff, 0x8d, 0x6c, 0x30, 0x03, 0x92, 0xf8, 0x31, 0x65, 0x29,
	0x8d, 0xe6, 0x96, 0xca, 0x53, 0x72, 0x08, 0x3d, 0x03, 0x7d, 0xe6, 0xa7, 0x74, 0x49, 0x2c, 0xcd,
	0x56, 0x06, 0x1d, 0xbc, 0x3a, 0xa1, 0xe7, 0xd0, 0xb9, 0x5e, 0x92, 0x38, 0x29, 0x68, 0xba, 0xad,
	0x0c, 0x34, 0xdc, 0xbe, 0x12, 0x47, 0xb4, 0x07, 0x70, 0xed, 0xf3, 0x52, 0x82, 0x61, 0x6a, 0xb5,
	0x6d, 0x65, 0xa0, 0x62, 0xe3, 0xa4, 0x0c, 0xf0, 0x74, 0xc6, 0x82, 0x55, 0xba, 0x23, 0xd2, 0xd3,
	0x32, 0x20, 0xb3, 0xbd, 0xdc, 0x32, 0x78, 0x45, 0x25, 0xdb, 0xcb, 0x65, 0xb6, 0x97, 0x5b, 0x20,
	0xd2, 0xd3, 0x32, 0x80, 0x4e, 0xa1, 0x9b, 0x30, 0xe2, 0xd3, 0x6f, 0xd4, 0x9f, 0xf1, 0x2b, 0x99,
	0xb6, 0x3a, 0x30, 0x8f, 0x5e, 0xb8, 0xff, 0x9b, 0xe9, 0x5e, 0xca, 0x40, 0x5c, 0xe5, 0xa1, 0xf7,
	0x60, 0x2c, 0x67, 0x31, 0x15, 0x22, 0x3b, 0x5c, 0x64, 0xaf, 0x4e, 0xe4, 0xaa, 0x04, 0xe1, 0x35,
	0x9e, 0x37, 0x43, 0xd4, 0xf4, 0xd8, 0x8c, 0xad, 0x37, 0xe3, 0x23, 0xec, 0x7c, 0xce, 0x48, 0x9c,
	0x63, 0xb2, 0x20, 0xd9, 0x86, 0xad, 0x58, 0x1b, 0xad, 0xca, 0x46, 0x3b, 0x07, 0xd0, 0xfd, 0x40,
	0x6e, 0xc9, 0x9d, 0x7d, 0x75, 0x7e, 0x2b, 0xd0, 0xad, 0x5c, 0xe5, 0x81, 0x3a, 0xbf, 0x0f, 0x90,
	0xcd, 0xe9, 0x22, 0x23, 0xe3, 0x82, 0xdb, 0xe2, 0x00, 0x29, 0x22, 0x1c, 0xba, 0xcd, 0x48, 0x61,
	0x03, 0x1f, 0x81, 0xdd, 0xbb, 0x1c, 0x5a, 0x81, 0xf0, 0x1a, 0x8f, 0x9e, 0x82, 0xc6, 0x0f, 0x7c,
	0x3c, 0x0c, 0x2c, 0x0e, 0xce, 0x2f, 0x05, 0x8c, 0xbf, 0x86, 0x6e, 0xe3, 0x1a, 0xda, 0x83, 0x5c,
	0xe3, 0xbb, 0x0a, 0xe6, 0xc5, 0x9a, 0xfa, 0xf8, 0x25, 0x6e, 0xef, 0x4b, 0x9c, 0xc0, 0x13, 0xa9,
	0x13, 0x67, 0x34, 0x49, 0xd1, 0x10, 0x4c, 0x89, 0x66, 0x29, 0x5c, 0xf1, 0xa0, 0x4e, 0x51, 0x62,
	0x62, 0x99, 0xf3, 0xca, 0x2d, 0xc6, 0xb4, 0x9c, 0x81, 0x0e, 0xb4, 0x26, 0xa3, 0x2f, 0x93, 0x5e,
	0x03, 0x01, 0xe8, 0xe3, 0xe9, 0x27, 0x6f, 0x84, 0x7b, 0x0a, 0x32, 0xa1, 0xed, 0x9d, 0x9f, 0x9f,
	0x8d, 0x86, 0xe3, 0x5e, 0xf3, 0xe8, 0xa7, 0x0a, 0x48, 0x12, 0xbb, 0x14, 0xaf, 0x29, 0x1a, 0x83,
	0x2e, 0xec, 0x44, 0xb5, 0xae, 0x54, 0xde, 0xd6, 0xfe, 0x7d, 0x15, 0x3a, 0x8d, 0x42, 0x4f, 0xf8,
	0x5f, 0xaf, 0x57, 0x79, 0x1e, 0x36, 0xd1, 0x7b, 0x07, 0xea, 0x29, 0x49, 0x51, 0xb7, 0x44, 0x8e,
	0x42, 0x96, 0xe6, 0x9b, 0x10, 0x8f, 0xa1, 0xc5, 0xad, 0xfe, 0x87, 0xf9, 0xf2, 0x1e, 0x66, 0xc1,
	0x71, 0x1a, 0xe8, 0x02, 0x34, 0xbe, 0x3d, 0x91, 0x5d, 0x87, 0x97, 0x17, 0xeb, 0xa6, 0x8a, 0xc7,
	0xa0, 0x8b, 0x1d, 0x5a, 0x6f, 0x4c, 0x65, 0xbf, 0xf6, 0xab, 0x45, 0x3b, 0x0d, 0xaf, 0xfd, 0x55,
	0x63, 0x34, 0x64, 0x37, 0x37, 0x3a, 0xff, 0xdf, 0xf3, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xf4, 0xf6, 0x61, 0xf6, 0x47, 0x09, 0x00, 0x00,
}
